# Generated by Django 5.0.2 on 2024-04-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_account_cart_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images')),
                ('title', models.CharField(max_length=40)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
