# Generated by Django 5.0.4 on 2024-05-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0006_deal_alter_cart_product_cart_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
